dist: xenial   # required for Python >= 3.7
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"


before_install:
  - python --version

  # Download Axon Server.
  - ./dev/download_axon_server.sh

  # Run Axon Server.
  - ./axonserver/axonserver.jar &
  - sleep 60  # wait for the server to start (replace this with polling?)

install:
  - pip install -U virtualenv
  - virtualenv --python=python ../venv
  - source ../venv/bin/activate
  - which python
  - python --version
  - pip install -U pip wheel
  - pip install python-coveralls
  - pip install -U "coverage<5.0.0"  # v5 is incompatible ATM.

script:
- if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then
      coverage run -m unittest discover axonclient -v;
  fi

- if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then
      python -m unittest discover eventsourcing.tests -v;
  fi

after_success:
- if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then
      coverage combine;
      coveralls;
  fi
